mysite/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 关于用户操作的路由
    url(r"^$", views.index),
    url(r"^index/$", views.index, name="index"),
    url(r"^add_user/$", views.add_user, name="add_user"),
    # url(r"^delete_user/$", views.delete_user, name="delete_user"),
    # url(r"^(\d+)delete_user/$", views.delete_user, name="delete_user"),
    #\d代表匹配任意一个字符，/d无意义
    url(r"^delete_user/(?P<user_id>\d+)/$", views.delete_user, name="delete_user"),
    url(r"^list_user/$", views.list_user, name="list_user"),
    url(r"^reg/$", views.reg, name="reg"),
    url(r"^show/(\d+)/$", views.show, name="show"),
    # url(r"^(?P<u_id>\d+)/show/$", views.show, name="show"),
    url(r"^(?P<u_id>\d+)/update/$", views.update, name="update"),
    url(r"^update_pwd/$", views.update_pwd, name="update_pwd"),
    # url(r"^update_header/$", views.update_header, name="update_header"),
    url(r"^login/$", views.login, name="login"),
    url(r"^logout/$", views.logout, name="logout"),

    # 文章操作的路由
    url(r"^add_article/$", views.add_article, name="add_article"),
    url(r"^(?P<a_id>\d+)/delete_article/$", views.delete_article, name="delete_article"),
    url(r"^(?P<a_id>\d+)/update_article/$", views.update_article, name="update_article"),
    url(r"^(?P<a_id>\d+)/show_article/$", views.show_article, name="show_article"),
    url(r"^show_all_articles/$", views.show_all_articles, name="show_all_articles"),

    url(r"^code/$", views.code, name="code"),
    url(r"^ajax_hello/$", views.ajax_hello, name="ajax_hello"),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models()


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r"^$", include("blog.urls")),
    url(r'^blog/', include("blog.urls", namespace="blog")),
    url(r'^ueditor/', include('DjangoUeditor.urls'))
]

mysite/blog/models.py
from django.db import models
from DjangoUeditor.models import UEditorField


class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, verbose_name="用户名称")
    password = models.CharField(max_length=255, verbose_name="用户密码")
    age = models.IntegerField(default=18, verbose_name="用户年龄")
    nickname = models.CharField(max_length=255, verbose_name="用户昵称")
    birthday = models.DateTimeField(auto_now=True)
    header = models.ImageField(upload_to='static/img/headers/', default="static/img/default.png", verbose_name="用户头像")

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.nickname


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, verbose_name="文章标题")
    content = UEditorField()
    publishTime = models.DateField(auto_now_add=True)
    modifyTime = models.DateField(auto_now=True)

    # 外键
    # 一对一
    # author = models.OneToOneField
    # 一对多
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 多对多
    # author = models.ManyToManyField

    class Meta:
        ordering = ["-publishTime"]

    def __str__(self):
        return self.title

mysite/blog/views.py
from io import BytesIO
import uuid

from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.shortcuts import reverse
from django.core.cache import cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET,require_http_methods, require_POST,require_safe
from django.forms.models import model_to_dict
from django.core.serializers import serialize

from . import models
from . import utils
from . import cacheUtils


# 博客首页
def index(request):
    articles = cacheUtils.getAllArticle()
    return render(request, "blog/index.html", {"articles": articles})

# 添加用户
def add_user(request):
    return render(request, "blog/add_user.html", {})

# 删除用户
def delete_user(request, user_id):
    # u_id = request.GET["id"]
    user = models.User.objects.get(pk=user_id)
    user.delete()
    # return render(request, "blog/list_user.html", {})
    # return HttpResponseRedirect("/blog/list_user/")
    return redirect("/blog/list_user/")

# 查看所有用户列表
def list_user(request):
    users = models.User.objects.all()
    return render(request, "blog/list_user.html", {"users": users})


# 用户注册
def reg(request):
    if request.method == "GET":
        return render(request, "blog/add_user.html", {"msg": "请认真填写如下选项"})
    elif request.method == "POST":
        # 接受参数
        try:
            username = request.POST["username"].strip()
            password = request.POST.get("password").strip()  # .getlist()
            confirmpwd = request.POST.get("confirmpwd").strip()
            nickname = request.POST.get("nickname", None)
            code = request.POST['code']
            avatar = request.FILES.get("avatar", 'static/img/headers/default.png')

            mycode = request.session['code']
            if code.upper() != mycode.upper():
                return render(request, "blog/add_user.html", {"msg": "验证码错误，请重新输入！"})
            # 删除session中的验证码
            del request.session['code']

            # 数据校验
            if len(username) < 1:
                return render(request, "blog/add_user.html", {"msg": "用户名称不能为空！！"})
            if len(password) < 6:
                return render(request, "blog/add_user.html", {"msg": "密码长度不能小于6位！！"})
            if password != confirmpwd:
                return render(request, "blog/add_user.html", {"msg": "两次密码不一致！！"})
            # 用户名称是否重复
            try:
                user = models.User.objects.get(name=username)
                return render(request, "blog/add_user.html", {"msg": "该用户名称已经存在，请重新填写！！"})
            except:
                # 保存数据
                password = utils.hmac_by_md5(password)

                user = models.User(name=username, password=password, nickname=nickname, header=avatar)
                user.save()
                return render(request, "blog/add_user.html", {"msg": "恭喜您，注册成功！！"})
        except:
            return render(request, "blog/add_user.html", {"msg": "对不起，用户名称不能为空！！"})


# 展示单个用户信息
def show(request, u_id):
    user =  models.User.objects.get(pk=u_id)
    return render(request, "blog/show.html", {"user": user})


# 修改用户信息
def update(request, u_id):
    if request.method == "GET":
        user = models.User.objects.filter(id=u_id).first()
        return render(request, "blog/update.html", {"user": user})
    else:
        nickname = request.POST["nickname"]
        age = request.POST["age"]

        # 数据校验
        if int(age) < 0:
            return render(request, "blog/update.html", {"msg": "好好在娘胎里待着，不要作妖"})
        if int(age) > 100:
            return render(request, "blog/update.html", {"msg": "年龄太大就安静一点吧"})

        # 修改数据
        # 获取用户
        user = models.User.objects.get(pk=u_id)
        # 修改数值
        user.age = age
        user.nickname = nickname
        # 保存
        user.save()

        return redirect("/blog/show/" + str(u_id) + "/")
        # return redirect("/blog/show", args(u_id, ))
        # return redirect(reverse("blog:show",args=(u_id,)))


# 修改用户密码
def update_pwd(request):
    if request.method == "GET":
        # 获取用户
        user = request.session['loginUser']
        return render(request, "blog/update_pwd.html", {"msg": "请正确填写修改信息！"}, {"user": user})
    elif request.method == "POST":
        # 获取输入信息
        oldpassword = request.POST["oldpassword"]
        oldpassword = utils.hmac_by_md5(oldpassword)
        password = request.POST['password'].strip()
        confirmpwd = request.POST['confirmpwd']

        # 获取用户
        user = request.session['loginUser']
        # 判断输入信息
        if oldpassword != user.password:
            return render(request, "blog/update_pwd.html", {"msg": "原密码输入错误，请重新输入！"})
        elif password != confirmpwd:
            return render(request, "blog/update_pwd.html", {"msg": "两次输入的密码不一致，请重新输入！"})
        else:
            # 密码加密并覆盖原密码
            password = utils.hmac_by_md5(password)
            user.password = password

            # 保存
            user.save()
            return redirect(reverse("blog:logout"))


# 修改用户头像
def update_header(request):
    # 获取用户
    user = request.session['loginUser']
    if request.method == "GET":
        return render(request, "blog/update_pwd.html", {"msg": "请正确填写修改信息！"}, {"user": user})
    elif request.method == "POST":
        avatar = request.FILES.get("avatar")

        # 覆盖原头像并保存
        user.header = avatar
        user.save()
        return render(request, "blog/show.html", {"msg": "对不起，用户名称不能为空！！"})


# 用户登录
def login(request):
    if request.method == "GET":
        return render(request, "blog/login.html", {"msg": "欢迎登录"})
    elif request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        code = request.POST['code']

        mycode = request.session['code']
        if code.upper() != mycode.upper():
            return render(request, "blog/login.html", {"msg": "验证码错误，请重新输入！"})
        # 删除session中的验证码
        del request.session['code']

        try:
            password = utils.hmac_by_md5(password)
            user = models.User.objects.get(name=username, password=password)
            # 使用session来记录用户的登录信息
            request.session["loginUser"] = user
            # 使用cookie记住用户名称
            response = redirect(reverse("blog:index"))
            # cookie不能存储中文
            response.set_cookie("username", user.name, max_age=3600 * 24 * 14)
            return response
        except:
            return render(request, "blog/login.html", {"msg": "账号密码错误，请重新输入！"})


# 用户退出
def logout(request):
    try:
        del request.session["loginUser"]
    finally:
        return redirect(reverse("blog:index"))


# 添加文章
def add_article(request):
    if request.method == "GET":
        return render(request, "blog/add_article.html", {"msg": "请开始你的表演"})
    else:
        title = request.POST["title"].strip()
        content = request.POST["content"]
        author = request.session["loginUser"]

        article = models.Article(title=title, content=content, author=author)
        article.save()

        # 将缓存重新更新
        cacheUtils.getAllArticle(ischange=True)
        return redirect(reverse("blog:show_article", kwargs={"a_id": article.id}))


# 删除文章
def delete_article(request, a_id):
    article = models.Article.objects.get(pk=a_id)
    article.delete()
    # 更新缓存
    cacheUtils.getAllArticle(ischange=True)
    return redirect(reverse("blog:index"))

# 修改文章
def update_article(request, a_id):
    article = models.Article.objects.get(pk=a_id)
    if request.method == "GET":
        return render(request, "blog/update_article.html", {"article": article})
    else:
        title = request.POST["title"].strip()
        content = request.POST["content"]
        article.title = title
        article.content = content
        article.save()

        return redirect(reverse("blog:show_article", kwargs={"a_id": a_id}))

# 查看文章
def show_article(request, a_id):
    article = models.Article.objects.get(pk=a_id)
    return render(request, "blog/show_article.html", {"article": article})


#展示单个用户所有的文章
def show_all_articles(request):
    articles = models.Article.objects.all()
    return render(request, "blog/show_all_articles.html", {"articles": articles})


def code(request):
    image, code = utils.create_code()
    # 首先需要将我们的code保存到我们的session中
    request.session['code'] = code
    # 返回图片
    file = BytesIO()
    image.save(file, 'PNG')

    return HttpResponse(file.getvalue(), "image/png")

@require_POST
@csrf_exempt # 这个装饰器，表示装饰者的函数忽略csrf验证
# @require_http_methods("GET", "POST")
def ajax_hello(request):
    # id = request.POST['id']
    # article = models.Article.objects.get(pk=id)
    # msg = {
    #     "id": user.id,
    #     "uname": user.name,
    #     "unickname": user.nickname,
    #     "uage": user.age,
    # }
    # JsonResponse 返回一个字段对象，会自动完成dict --> json的转换
    # return JsonResponse(model_to_dict(article))
    # HttpResponse返回的是一个字符串
    # return HttpResponse(msg)

    # jqueryset django考虑到大家需要传输，提供了一个序列化
    ats = models.Article.objects.all()

    return HttpResponse(serialize("json", ats))

mysite/blog/templates/blog/add_article.html
{% extends 'base.html' %}


{% block title %} 添加文章 {% endblock %}
{% block content %}
<!-----------------------------------发布文章-------------------------------------->
<script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.all.min.js"></script>

<div class="container">
    <div class="row yonghuzhuce">
        <div class="col-md-offset-2 col-md-8">
            <h3><strong>发表文章</strong></h3>
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <strong>{{msg}}</strong>
            </div>

            <form class="form-horizontal" action="/blog/add_article/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-md-offset-1 col-md-10">
                        <input type="text" class="form-control" name="title" id="title" placeholder="请输入文章标题" autocomplete="off">
                    </div>
                </div>

                <div class="form-group">
                    <div class="">
                        <textarea name="content" class="col-md-offset-1 col-md-10" id="content" cols="100" rows="30" placeholder="在此输入你想输入的内容"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-5 col-sm-6">
                        <button type="submit" class="btn btn-default">发表</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    var ue = UE.getEditor('content', {
        'initialFrameWidth': 620,
        'initialFrameHeight': 500,
        'serverUrl': '/ueditor/controller/?imagePathFormat=&filePathFormat=',
//        toolbars: [
//            ['fullscreen', 'source', 'undo', 'redo', 'bold']
//        ]
    });
</script>
{% endblock %}

mysite/blog/templates/blog/add_user.html
{% extends 'base.html' %}


{% block title %} 注册 {% endblock %}
{% block content %}
<!-----------------------------------注册界面------------------------------------------>
<div class="container">
    <div class="row yonghuzhuce">
        <div class="col-md-offset-2 col-md-8">
            <h3><strong>用户注册</strong></h3>
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <strong>{{msg}}</strong>
            </div>

            <form class="form-horizontal" action="/blog/reg/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="nickname" class="col-sm-2 control-label">昵&nbsp;&nbsp;称&nbsp;&nbsp;</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="nickname" id="nickname" placeholder="请输入昵称（支持中英文）" autocomplete="off">
                    </div>
                </div>

                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">账&nbsp;&nbsp;号&nbsp;&nbsp;</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="username" id="username" placeholder="请输入账号" autocomplete="off">
                    </div>
                </div>

                <div class="form-group">
                    <label for="avatar" class="col-sm-2 control-label">用户头像：</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control"  name="avatar" id="avatar" >
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">密&nbsp;&nbsp;码&nbsp;&nbsp;</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="password1" placeholder="请输入密码">
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">确认密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="confirmpwd" id="password2" placeholder="请确认您的密码">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        <a href="#" onclick="changeCode()"><img id="code" src="{% url 'blog:code' %}" alt="验证码" title="点击刷新"></a>
                    </div>
                    <div class="col-md-4">
                        <input type="text" name="code" placeholder="请输入左侧验证码">
                    </div>
                </div>
                <!--<div class="form-group">-->
                    <!--<div class="col-sm-offset-2 col-sm-10">-->
                        <!--<div class="checkbox">-->
                            <!--<label>-->
                                <!--<input type="checkbox"> Remember me-->
                            <!--</label>-->
                        <!--</div>-->
                    <!--</div>-->
                <!--</div>-->

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">注册</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function changeCode() {
//            document.getElementById("code").src = "/blog/code?id="+ new Date().getTime()
        document.getElementById("code").src = "/blog/code?id="+ Math.random()
    }
</script>
{% endblock %}

mysite/blog/templates/blog/list_user.html
{% extends 'base.html' %}


{% block title %} 用户列表 {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <!-- 轮播图 -->
        <div class="col-md-8">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                      <img src="/static/blog/img/articles/1.jpg" alt="...">
                      <div class="carousel-caption">
                        欢迎来到六千l博客
                      </div>
                    </div>
                    <div class="item">
                        <img src="/static/blog/img/articles/121.jpg" alt="...">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    <div class="item">
                        <img src="/static/blog/img/articles/1234.jpg" alt="...">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    <div class="item">
                        <img src="/static/blog/img/articles/1235.jpg" alt="...">
                        <div class="carousel-caption">
                        </div>
                    </div>
                </div>

                <!-- 控制换图按钮 -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">上一张</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">下一张</span>
                </a>
            </div>
        </div>
        <!-- 广告位 -->
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">博客简介</div>
                <div class="panel-body">
                    <p>
                        三月长，梨花旺。 <br /><br />
                        犁牛行，农夫忙。 <br /><br />
                        一朝铁蹄来，一朝金戈响。 <br /><br />
                        入伍行，作兵将。 <br /><br />
                        三年征夫死，十年将军苍。 <br /><br />
                        同袍问，何处是故乡。 <br /><br />
                        你莫哭，你莫慌。 <br /><br />
                        且饮一杯酒，且进一寸枪。 <br /><br />
                        你应他，此身葬处是故乡。
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">博主信息</div>
                    <ul class="list-group">
                        <li class="list-group-item" style="text-align: center">
                            <a href="">
                                <img src="/{{ request.session.loginUser.header }}" width="100" height="100" alt="..." class="img-circle">
                            </a>
                            <strong>{{ request.session.loginUser.nickname }}</strong>
                        </li>
                        <li class="list-group-item">
                            <a href="/blog/index/">博客首页</a>
                        </li>
                        <li class="list-group-item">
                            <a href="/blog/list_user/">查看所有用户</a>
                        </li>
                        <li class="list-group-item">
                            <a href="/blog/show_all_articles/">查看所有文章</a>
                        </li>
                        <li class="list-group-item">
                            <a href="/blog/add_article/">发表文章</a>
                        </li>
                    </ul>
            </div>
        </div>

        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">所有用户</div>
                <div class="panel-body">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <td>用户标识</td>
                            <td>用户名称</td>
                            <td>用户昵称</td>
                            <td>用户年龄</td>
                            <td>用户生日</td>
                            <td>操作</td>
                        </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                                <tr>
                                    <td>{{ forloop.counter0}}</td>
                                    <td>{{ user.name}}</td>
                                    <td><a href="/blog/show/{{ user.id }}">{{ user.nickname}}</a></td>
                                    <td>{{ user.age}}</td>
                                    <td>{{ user.birthday}}</td>
                                    <td>
                                        <a href="/blog/{{user.id}}/update/">修改</a>
                                        <a onclick="window.confirm('您确定要删除这个用户吗？')" href="/blog/delete_user/{{user.id}}/">删除</a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="6">对不起，当前没有用户</td>
                                </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/blog/templates/blog/login.html
{% extends 'base.html' %}


{% block title %} 登录 {% endblock %}
{% block content %}
<!-----------------------------------用户登录-------------------------------------->
<div class="container">
    <div class="row yonghudenglu">
        <div class="col-md-8 col-md-offset-2">
            <h3><strong>用户登录</strong></h3>
            <!--<div style="color: red;">{{msg}}</div>-->
            <!--<div class="alert alert-danger" role="alert">{{msg}}</div>-->
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{{msg}}</strong>
            </div>

            <form class="form-horizontal" action="/blog/login/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">账&nbsp;&nbsp;&nbsp;&nbsp;号&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" value="{{username}}" name="username" id="username" placeholder="请输入您的账号" autocomplete="off">
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">密&nbsp;&nbsp;&nbsp;&nbsp;码&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="password" placeholder="请输入您的密码">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-2">
                        <a href="#" onclick="changeCode()"><img id="code" src="{% url 'blog:code' %}" alt="验证码" title="点击刷新"></a>
                    </div>
                    <div class="col-md-4">
                        <input type="text" name="code" placeholder="请输入左侧验证码">
                    </div>
                </div>


                <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">登录</button>
                </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function changeCode() {
//            document.getElementById("code").src = "/blog/code?id="+ new Date().getTime()
        document.getElementById("code").src = "/blog/code?id="+ Math.random()
    }
</script>
<!-----------------------------------登录框-------------------------------------->
{% endblock %}

mysite/blog/templates/blog/update_pwd.html
{% extends 'base.html' %}


{% block title %} 修改密码 {% endblock %}
{% block content %}
<div class="container">
    <div class="row yonghuzhuce">
        <div class="col-md-offset-2 col-md-8">
            <h3><strong>修改密码</strong></h3>
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <strong>{{msg}}</strong>
            </div>

            <form class="form-horizontal" action="/blog/update_pwd/" method="post">
                {% csrf_token %}
                <!--<div class="form-group">-->
                    <!--<label for="nickname" class="col-sm-2 control-label">昵&nbsp;&nbsp;称&nbsp;&nbsp;</label>-->
                    <!--<div class="col-sm-10">-->
                        <!--<input type="text" class="form-control" name="nickname" id="nickname" placeholder="请输入昵称（支持中英文）" autocomplete="off">-->
                    <!--</div>-->
                <!--</div>-->

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">原密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="oldpassword" id="oldpassword" placeholder="请输入原密码" autocomplete="off">
                    </div>
                </div>

                <!--<div class="form-group">-->
                    <!--<label for="avatar" class="col-sm-2 control-label">用户头像：</label>-->
                    <!--<div class="col-sm-10">-->
                        <!--<input type="file" class="form-control"  name="avatar" id="avatar" >-->
                    <!--</div>-->
                <!--</div>-->

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">新密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="password1" placeholder="请输入新密码">
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">确认密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="confirmpwd" id="password2" placeholder="请确认您的新密码">
                    </div>
                </div>

                <!--<div class="form-group">-->
                    <!--<div class="col-md-offset-2 col-md-2">-->
                        <!--<a href="#" onclick="changeCode()"><img id="code" src="{% url 'blog:code' %}" alt="验证码" title="点击刷新"></a>-->
                    <!--</div>-->
                    <!--<div class="col-md-4">-->
                        <!--<input type="text" name="code" placeholder="请输入左侧验证码">-->
                    <!--</div>-->
                <!--</div>-->
                <!--<div class="form-group">-->
                    <!--<div class="col-sm-offset-2 col-sm-10">-->
                        <!--<div class="checkbox">-->
                            <!--<label>-->
                                <!--<input type="checkbox"> Remember me-->
                            <!--</label>-->
                        <!--</div>-->
                    <!--</div>-->
                <!--</div>-->

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">修改</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!--<script>-->
    <!--function changeCode() {-->
<!--//            document.getElementById("code").src = "/blog/code?id="+ new Date().getTime()-->
        <!--document.getElementById("code").src = "/blog/code?id="+ Math.random()-->
    <!--}-->
<!--</script>-->
{% endblock %}